### ISSUE TITLE
Nextcloud 28 breaks opening EPUBs (it downloads instead)

### ISSUE THREAD

**Issue by joelcollet** [devnoname120/epubviewer#8]
Nextcloud 28 version, in docker container
App version 1.5.3
Using .epub files without DRM. 
in the app configuration epub as well as pdf are correctly checked.
when clicking on the file, it is downloaded instead of being opened in app. tried on firefox and edge navigator
pdf file are however correctly opened in the app.

is there any file type association to perform ?

Jo

**Comment by veizour** [comment]
I'm having the same issue. The built in PDF viewer works, but the ebook reader appears to not auto-load. Even if I select "PDF" as a default option, the built in PDF viewer still opens, while epub/cbr/etc go direct to download.

**Comment by he-sb** [comment]
Same issue, is there anyone can help us?

**Comment by devnoname120** [comment]
Feel free to do a PR. I'm not interested in fixing it on my own at this time.

**Comment by hbarel** [comment]
> Feel free to do a PR. I'm not interested in fixing it on my own at this time.

It's fair not to want to put your resources into it.

It might be nice, however, to remove it's compatibility with NC 28 until someone fixes it. After all, it's in the official app repository and people download it expecting it to work out of the box...

**Comment by maxmbed** [comment]
I have checked the log of epubviewer inside my nextcloud appache-apps container and it likely prompts an error: `Fatal    no app in context  Error: Call to undefined method` when I am opening any epub file from the Nextcloud file manager.

To reproduce the case:

```bash
docker exec -u 33 -it nextcloud-apache-app-1 bash
php occ log:watch
``` 
Then in Nextcloud file manager, try to open your epub file
And the log prompt:
```bash
  Fatal    no app in context  Error: Call to undefined method OCA\Richdocuments\Service\DiscoveryService::refetch() at .../richdocuments/lib/AppInfo/Application.php line 226                                                                                2024-01-26T18:00:02+00:00

                              0. custom_apps/richdocuments/lib/AppInfo/Application.php line 154
                                 OCA\Richdocuments\AppInfo\Application->checkAndEnableCODEServer(

                                 )
                              1. lib/private/AppFramework/Bootstrap/Coordinator.php line 200
                                 OCA\Richdocuments\AppInfo\Application->boot(["OC\\AppFramework\\Bootstrap\\BootContext"])
                              2. lib/private/App/AppManager.php line 434
                                 OC\AppFramework\Bootstrap\Coordinator->bootApp("richdocuments")
                              3. lib/private/App/AppManager.php line 213
                                 OC\App\AppManager->loadApp("richdocuments")
                              4. lib/private/legacy/OC_App.php line 125
                                 OC\App\AppManager->loadApps([])
                              5. ocs/v1.php line 59
                                 OC_App::loadApps(

                                 )
                              6. ocs/v2.php line 23
                                 require_once("\/var\/www\/html\/ocs\/v1.php")
```

Not a php/web guy, so can't say more than the discovery service thing is not happy.

**Comment by devnoname120** [comment]
@maxmbed Could you run `occ app:disable richdocumentscode` and report back? This particular issue seems unrelated to the `epubviewer` app.

Related: https://github.com/nextcloud/richdocuments/issues/3363

**Comment by maxmbed** [comment]
@devnoname120 
Disable richdocument app stop the error prompt I saw in the log.
This is indeed unrelated to our case.

**Comment by devnoname120** [comment]
@maxmbed And you don't see any other logs? For example if you go to the settings, tick and untick the file types in the `epubviewer` configuration, etc.

**Comment by maxmbed** [comment]
I have tried to look at different location within the container but was not an easy to guess where the look first.

Now you are telling, I can actually see errors in Nextcloud log admin page about epubviewer

```json
{
  "reqId": "RwJY4TrcxW4ZVWqUWWQB",
  "level": 0,
  "time": "2024-01-26T19:56:07+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "epubviewer",
  "method": "",
  "url": "--",
  "message": "/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.",
  "userAgent": "--",
  "version": "28.0.1.1",
  "data": {
    "app": "epubviewer"
  },
  "id": "65b411d98af08"
}
```
About this:

> go to the settings, tick and untick the file types in the epubviewer configuration

I am not sure what do you mean.

**Comment by devnoname120** [comment]
@maxmbed In the file `appinfo/app.php`, can you try replacing this:

```php
Util::addscript('epubviewer', 'plugin');
```

With this:

```php
Util::addInitScript('epubviewer', 'plugin');
```

?

**Comment by maxmbed** [comment]
No editor in this container.
But fortunately but sed can help
```bash
sed -i 's/addscript/addInitScript/g' app.php'
```
It does not seem to be effective when I tried to open my epub file.
Is there something else to do ? Like a restart ?

**Comment by devnoname120** [comment]
OK looks like I will need to get my hand dirty and debug. It's probably not going to happen before Hetzner upgrades to Nextcloud 28 which should not take too much time (as soon as Nextcloud 29 is out).

**Comment by michaave** [comment]
> @maxmbed In the file `appinfo/app.php`, can you try replacing this:
> 
> ```
> Util::addscript('epubviewer', 'plugin');
> ```
> 
> With this:
> 
> ```
> Util::addInitScript('epubviewer', 'plugin');
> ```
> 
> ?

I've made this change to the file, but there is no change to the app's behavior.

**Comment by devnoname120** [comment]
@fcki1984 Could you try to fix this using ChatGPT?

**Comment by drpetersen** [comment]
A big Thank You, this works for me (NC 29.0.0 beta 1)!

**Comment by teledyn** [comment]
Oh yes! This is lovely! Works fine on 28.0.3.2!

**Comment by devnoname120** [comment]
Anyone to test it on NC 27? Then I'll publish a new release if it works too!

**Comment by devnoname120** [comment]
I tested it on Nextcloud 27 and it works great. I just pushed a release to the app store.

If you guys could review the app it would be great because its rating tanked a lot, which reduces its visibility compared to the other (non-working) EPUB reader apps.

https://apps.nextcloud.com/apps/epubviewer

**Comment by he-sb** [comment]
Huge thanks!

New release works perfect on `28.0.3` , and also works fine in shared folder.

**Comment by hbarel** [comment]
On my 28.0.3 I noticed that settings are not saved between sessions.

**Comment by devnoname120** [comment]
@hbarel Could you take a video that reproduces the problem entirely and give me the logs? Browser console logs + Nextcloud server logs.

**Comment by ummon29** [comment]
I too have Problems on Nextcloud 27.1.7 (on RaspberrypiOS). Opening an cbz or epub tries to download them. I also can't change any configuration. Reloading after changing the configuration brings the old configuration back.
I come from the 1.5.0 of the Xefir Repository. I believe I have the problem with the configuration since testing patches in an old 1.4.x Version. So, maybe I only need to reset my App properly. Is there anywhere a list of the tables that need to be dropped to reset this App properly or even better a short howto?

**Comment by devnoname120** [comment]
Can you guys give me logs? I can't debug anything without logs.

**Comment by ummon29** [comment]
Those are the things I find in my log regarding epubviewer or without app context after:
1. activating the app.
2. trying to open an epub
3. trying to change the configuration

The messages about scrips and epubviewer-main.css appeared multiple times and may be connected because the seem to appear always together.

[no app in context] Debug: Deprecated event type for \OCP\Collaboration\Resources::loadAdditionalScripts: null

GET /apps/files/
from 192.168.x.x by xxx at 2024-03-11T22:26:41+00:00

[no app in context] Debug: Deprecated event type for OCA\Files::loadAdditionalScripts: Symfony\Component\EventDispatcher\GenericEvent is used

GET /apps/files/
from 192.168.x.x by xxx at 2024-03-11T22:26:41+00:00

[epubviewer] Debug: Could not find resource file "/apps/epubviewer/css/epubviewer-main.css"

GET /apps/files/
from 192.168.x.x by xxx at 2024-03-11T22:26:41+00:00

[no app in context] Debug: Deprecated event type for OCP\IDBConnection::CHECK_MISSING_PRIMARY_KEYS: Symfony\Component\EventDispatcher\GenericEvent is used

GET /settings/ajax/checksetup
from 192.168.x.x by xxx at 2024-03-11T22:28:48+00:00

[no app in context] Debug: Deprecated event type for OCP\IDBConnection::CHECK_MISSING_INDEXES: Symfony\Component\EventDispatcher\GenericEvent is used

GET /settings/ajax/checksetup
from 192.168.x.x by xxx at 2024-03-11T22:28:50+00:00

[no app in context] Debug: Deprecated event type for OCP\IDBConnection::CHECK_MISSING_COLUMNS: Symfony\Component\EventDispatcher\GenericEvent is used

GET /settings/ajax/checksetup
from 192.168.x.x by xxx at 2024-03-11T22:28:55+00:00

**Comment by maxmbed** [comment]
Confirm epub reader is working back on Nextcloud 28.0.3.
Thanks for the  support.
